
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username":"username",
    "password":"password"
}


###
GET http://localhost:3000/api/idea/all HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNTBjYjc0LTYyZTUtNDkzMy05NGQ0LWZmMGJjY2ZiOTZjYSIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUxMzgzOTQsImV4cCI6MTU2NTc0MzE5NH0.MUzkuq4_1ZLV7ER6-xbSzzWzUJB8CEa9-6Wdaf46XSY

###
POST http://localhost:3000/api/idea HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNTBjYjc0LTYyZTUtNDkzMy05NGQ0LWZmMGJjY2ZiOTZjYSIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUxMzgzOTQsImV4cCI6MTU2NTc0MzE5NH0.MUzkuq4_1ZLV7ER6-xbSzzWzUJB8CEa9-6Wdaf46XSY

{
	"idea":"idea",
	"desc":"desc"
}


###
POST http://localhost:3000/api/idea/6064f56b-8117-4b59-9f6b-eab7e5186817/bookmark HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNTBjYjc0LTYyZTUtNDkzMy05NGQ0LWZmMGJjY2ZiOTZjYSIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUxMzgzOTQsImV4cCI6MTU2NTc0MzE5NH0.MUzkuq4_1ZLV7ER6-xbSzzWzUJB8CEa9-6Wdaf46XSY
###
POST http://localhost:3000/api/idea/6064f56b-8117-4b59-9f6b-eab7e5186817/upvote HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNTBjYjc0LTYyZTUtNDkzMy05NGQ0LWZmMGJjY2ZiOTZjYSIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUxMzgzOTQsImV4cCI6MTU2NTc0MzE5NH0.MUzkuq4_1ZLV7ER6-xbSzzWzUJB8CEa9-6Wdaf46XSY
###
DELETE  http://localhost:3000/api/idea/7d373323-6104-4f48-9449-6a5c0e847ee5/downvote HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNTBjYjc0LTYyZTUtNDkzMy05NGQ0LWZmMGJjY2ZiOTZjYSIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUxMzgzOTQsImV4cCI6MTU2NTc0MzE5NH0.MUzkuq4_1ZLV7ER6-xbSzzWzUJB8CEa9-6Wdaf46XSY

###
GET http://localhost:3000/api/user/all HTTP/1.1