
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username":"username",
    "password":"password"
}


###
GET http://localhost:3000/api/idea/147a1662-3ca5-415e-a05c-c81e22595ab3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8

###
POST http://localhost:3000/api/idea HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8

{
	"idea":"idea",
	"desc":"desc"
}


###
POST http://localhost:3000/api/idea/6064f56b-8117-4b59-9f6b-eab7e5186817/bookmark HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8


###
POST http://localhost:3000/api/idea/6064f56b-8117-4b59-9f6b-eab7e5186817/upvote HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8


###
DELETE  http://localhost:3000/api/idea/7d373323-6104-4f48-9449-6a5c0e847ee5/downvote HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8


###
POST http://localhost:3000/api/comment/idea/147a1662-3ca5-415e-a05c-c81e22595ab3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8

{
	"comment":"comments7"
}


###
GET http://localhost:3000/api/comment/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8

###
GET http://localhost:3000/api/comment/idea/147a1662-3ca5-415e-a05c-c81e22595ab3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8


###
GET http://localhost:3000/api/comment/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8



###
GET http://localhost:3000/api/comment/idea/af54b354-6822-4225-9cc5-73bc1f116989 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8


###
GET http://localhost:3000/api/comment/c3c01500-01a9-43b1-b855-323967cd7189 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8



###
DELETE  http://localhost:3000/api/comment/730246ec-97b2-486a-a523-77a2e43aa0f8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYjgzZTQ2LTQ4MGItNGQ1NS04NWViLTc5ZGQyYTgwYzRkNCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NjUzMTE1NTQsImV4cCI6MTU2NTkxNjM1NH0.2gPQLRGFXLFJ4nSoIFlSJqXR9q8UohJivP_-0b8mFA8

###
GET https://appideagenerator.com/call.php HTTP/1.1